site_name: "${{ values.serviceName }} Docs"
repo_url: https://github.com/annaic/python-poetry-example
site_url: https://annaic.github.io/python-poetry-example
site_description: This is a template repository for Python projects that use Poetry for their dependency management.
site_author: Rajan Mahadevan
edit_uri: edit/main/docs/
repo_name: annaic/python-poetry-example
copyright: Maintained by <a href="https://annaic.com">Florian</a>.



nav:
  - Home: index.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ app ]